const data = [
    {
        id:1,
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqwPgPft-3YXJpliAmzG6KedAXBvG2Bt6B4arElN9rVA&s',
        name: 'The Shawshank Redemption',
        category : 'drama',
        duration : '2h 22m',
        imdb : '9.3',
        language: 'english',
        status : 'trending',
    },
    {
        id:2,
        img: 'https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg',
        name: 'The Godfather',
        category : 'crime',
        duration : '2h 55m',
        imdb : '9.2',
        language: 'english',
        status : 'upcoming',
    },
    {
        id:3,
        img: 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_FMjpg_UX1000_.jpg',
        name: 'The Dark Knight',
        category : 'action',
        duration : '2h 32m',
        imdb : '9.0',
        language: 'english',
        status : 'genres',
    },
    {
        id:4,
        img: 'https://m.media-amazon.com/images/M/MV5BMWMwMGQzZTItY2JlNC00OWZiLWIyMDctNDk2ZDQ2YjRjMWQ0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_FMjpg_UX1000_.jpg',
        name: 'The Godfather Part II',
        category : 'crime',
        duration : '3h 22m',
        imdb : '9.0',
        language: 'english',
        status : 'upcoming',
    },
    {
        id:5,
        img: 'https://m.media-amazon.com/images/M/MV5BMWU4N2FjNzYtNTVkNC00NzQ0LTg0MjAtYTJlMjFhNGUxZDFmXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_FMjpg_UX1000_.jpg',
        name: '12 Angry Men',
        category : 'crime',
        duration : '1h 36m',
        imdb : '9.0',
        language: 'english',
        status : 'genres',
    },
    {
        id:6,
        img: 'https://m.media-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_FMjpg_UX1000_.jpg',
        name: 'Schindler\'s List',
        category : 'biography',
        duration : '3h 15m',
        imdb : '9.0',
        language: 'english',
        status : 'upcoming',
    },
    {
        id:7,
        img: 'https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_QL75_UY281_CR2,0,190,281_.jpg',
        name: 'Pulp Fiction',
        category : 'crime',
        duration : '2h 34m',
        imdb : '8.9',
        language: 'english',
        status : 'trending',
    },
    {
        id:8,
        img: 'https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg',
        name: 'The Lord of the Rings: The Return of the King',
        category : 'adventure',
        duration : '3h 21m',
        imdb : '9.0',
        language: 'english',
        status : 'genres',
    },
    {
        id:9,
        img: 'https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_FMjpg_UX1000_.jpg',
        name: 'The Lord of the Rings: The Fellowship of the Ring',
        category : 'adventure',
        duration : '2h 58m',
        imdb : '8.9',
        language: 'english',
        status :'trending',
    },
    {
        id:10,
        img: 'https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
        name: 'Forrest Gump',
        category : 'romance',
        duration : '2h 22m',
        imdb : '8.8',
        language: 'english',
        status : 'upcoming',
    },
    {
        id:11,
        img: 'https://m.media-amazon.com/images/M/MV5BYjBhYmQxNTgtNDU2Ni00NGQzLTg5MzQtMDdkY2I3MzA1MTc0XkEyXkFqcGdeQXVyMTA0MTM5NjI2._V1_UX140_CR0,0,140,209_AL_.jpg',
        name: 'Gol Maal',
        category : 'romance',
        duration : '2h 24m',
        imdb : '8.5',
        language: 'hindi',
        status : 'upcoming',
    },
    {
        id:12,
        img: 'https://m.media-amazon.com/images/M/MV5BNTkyOGVjMGEtNmQzZi00NzFlLTlhOWQtODYyMDc2ZGJmYzFhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UY209_CR2,0,140,209_AL_.jpg',
        name: '3 Idiots',
        category : 'comedy',
        duration : '2h 50m',
        imdb : '8.4',
        language: 'hindi',
        status : 'genres',
    },
    {
        id:13,
        img: 'https://m.media-amazon.com/images/M/MV5BYWRjMDlmNGYtOGFhYy00ZWU4LTk3MzEtOTI4ZTgxN2Y5NGNkXkEyXkFqcGdeQXVyNzU3Nzk4MDQ@._V1_UX140_CR0,0,140,209_AL_.jpg',
        name: 'Black Friday ',
        category : 'action',
        duration : '2h 23m',
        imdb : '8.4',
        language: 'hindi',
        status : 'trending',
    },
    {
        id:14,
        img: 'https://m.media-amazon.com/images/M/MV5BMTQ4MzQzMzM2Nl5BMl5BanBnXkFtZTgwMTQ1NzU3MDI@._V1_UY209_CR4,0,140,209_AL_.jpg',
        name: 'Dangal',
        category : 'drama',
        duration : '2h 41m',
        imdb : '8.3',
        language: 'hindi',
        status : 'upcoming',
    },
    {
        id:15,
        img: 'https://m.media-amazon.com/images/M/MV5BYjY0MGU3MmQtMGVhOS00M2IyLWI1MTktZGUxMzBjMTE5ZDA3XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UY209_CR2,0,140,209_AL_.jpg',
        name: 'Like Stars on Earth ',
        category : 'family',
        duration : '2h 42m',
        imdb : '8.3',
        language: 'hindi',
        status : 'upcoming',
    },
    {
        id:16,
        img: 'https://m.media-amazon.com/images/M/MV5BMTMwMjk3MzA2OF5BMl5BanBnXkFtZTcwNjU2ODgzMQ@@._V1_UY209_CR4,0,140,209_AL_.jpg',
        name: 'Satya',
        category : 'crime',
        duration : '2h 50m',
        imdb : '8.3',
        language: 'hindi',
        status : 'upcoming',
    },
    {
        id:17,
        img: 'https://m.media-amazon.com/images/M/MV5BYjkzODdhZjUtMjY0YS00ODA3LTkxMDUtM2JlYTQyMWE1NTMzXkEyXkFqcGdeQXVyMzg1ODEwNQ@@._V1_UY209_CR5,0,140,209_AL_.jpg',
        name: 'Thirst ',
        category : 'action',
        duration : '2h 26m',
        imdb : '8.3',
        language: 'hindi',
        status : 'genres',
    },
    {
        id:18,
        img: 'https://m.media-amazon.com/images/M/MV5BODg4M2I0ZmMtMDFhMi00ZjkxLTk1NmItM2U5MDY3MGZhZDVkXkEyXkFqcGdeQXVyNTgyNTA4MjM@._V1_UX140_CR0,0,140,209_AL_.jpg',
        name: 'The Hero',
        category : 'action',
        duration : '1h 57m',
        imdb : '8.3',
        language: 'hindi',
        status : 'trending',
    },
    {
        id:19,
        img: 'https://m.media-amazon.com/images/M/MV5BOTM4ZjhiNGItMzE2My00YjM0LWE5ZTEtYTA5NDMzZDJlOWQ3XkEyXkFqcGdeQXVyODMyODMxNDY@._V1_UY209_CR2,0,140,209_AL_.jpg',
        name: 'Guide',
        category : 'action',
        duration : '3h 2m',
        imdb : '8.3',
        language: 'hindi',
        status : 'upcoming',
    },
    {
        id:20,
        img: 'https://m.media-amazon.com/images/M/MV5BMDE0Y2NhYjEtNWM3MS00MzFiLTlkODctYmViY2Q4OTczYWI2XkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_UY209_CR9,0,140,209_AL_.jpg',
        name: 'Jaane Bhi Do Yaaro ',
        category : 'comedy',
        duration : '2h 12m',
        imdb : '8.3',
        language: 'hindi',
        status : 'trending',
    },
]

export default data